name: DevSecOps Quality Gate

on:
  pull_request:
    branches:
      - main

jobs:
  tfsec_scan:
    name: Terraform SAST Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
        with:
          tfsec_args: Lab34
          github_token: ${{ secrets.GITHUB_TOKEN }}
